### ISSUE TITLE
Contribution to Linux kernel

### ISSUE THREAD

**Issue by madenvel** [ty2/goodix-gt7868q-linux-driver#6]
Hi,
6.10 is likely to be cut in the next couple of weeks, any plans to contribute this code to the kernel?

Thanks!

**Comment by ty2** [comment]
At this moment, I don't have any plans to handle this myself as I find it quite tedious. However, feel free to contribute the code to the kernel if you're interested.

Thanks.

**Comment by madenvel** [comment]
I submitted a patch (you CC'ed), no response yet.

**Comment by ty2** [comment]
> I submitted a patch (you CC'ed), no response yet.

I have received your email.

For others, you can keep track at https://lore.kernel.org/linux-input/20240716222757.22931-1-envelsavinds@gmail.com/T/#t

**Comment by Avenger-285714** [comment]
It is possible that the maintainer of the input subsystem may not have reviewed this commit. I will make some minor adjustments and resubmit it.

Upon further investigation, I have determined that this driver was a collaborative effort involving Terry Wong and two additional developers.

One of these developers is known by the GitHub username @mjy194 , however, I have been unable to locate his email address and therefore cannot include him in the mailing list.

Please accept my apologies for any inconvenience caused by this oversight.

**Comment by Avenger-285714** [comment]
See: https://lore.kernel.org/all/801C5D6FCE55F473+20240731154619.514470-1-wangyuli@uniontech.com/

Let's continue our endeavors to foster upstream support for this device and other devices exhibiting unconventional behavior.

Thank everyone.
